import { mutation } from "./_generated/server";

// Seed function to add demo cars
export const seed = mutation({
  handler: async (ctx) => {
    const existingCars = await ctx.db.query("cars").collect();
    if (existingCars.length > 0) {
      return { message: "Database already seeded", count: existingCars.length };
    }

    const demoCars = [
      {
        make: "Jeep",
        model: "Wrangler UNLTD Sahara 3.6L V6",
        year: 2013,
        price: 290000,
        mileage: 85000,
        fuelType: "Petrol",
        transmission: "Automatic",
        engineSize: "3.6L V6",
        color: "White",
        bodyType: "SUV",
        description:
          "Experience the perfect blend of rugged capability and refined comfort with the Jeep Wrangler. Powered by a 3.6 litre V6 engine paired with a smooth automatic transmission, this 4x4 is built to take you anywhere - from the city streets to the toughest trails - with confidence and style.",
        features: [
          "4x4 Capability",
          "Removable Roof",
          "Leather Seats",
          "Bluetooth",
          "Air Conditioning",
          "Alloy Wheels",
          "Cruise Control",
          "Power Windows",
        ],
        images: [
          "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=2671&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "BMW",
        model: "320i M Sport",
        year: 2019,
        price: 485000,
        mileage: 45000,
        fuelType: "Petrol",
        transmission: "Automatic",
        engineSize: "2.0L Turbo",
        color: "Black",
        bodyType: "Sedan",
        description:
          "The BMW 320i M Sport combines luxury with performance. This stunning sedan features the M Sport package with sportier styling, enhanced handling, and premium interior finishes. Perfect for those who demand excellence.",
        features: [
          "M Sport Package",
          "Sunroof",
          "Navigation",
          "Heated Seats",
          "Park Distance Control",
          "LED Headlights",
          "Apple CarPlay",
          "Reverse Camera",
        ],
        images: [
          "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=2670&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Mercedes-Benz",
        model: "C200 AMG Line",
        year: 2020,
        price: 595000,
        mileage: 32000,
        fuelType: "Petrol",
        transmission: "Automatic",
        engineSize: "2.0L Turbo",
        color: "Silver",
        bodyType: "Sedan",
        description:
          "Elegance meets performance in this Mercedes-Benz C200 AMG Line. With its distinctive AMG styling, premium leather interior, and advanced technology features, this luxury sedan delivers an exceptional driving experience.",
        features: [
          "AMG Line Package",
          "Ambient Lighting",
          "Burmester Sound",
          "Panoramic Sunroof",
          "Keyless Entry",
          "Electric Memory Seats",
          "360° Camera",
          "Active Brake Assist",
        ],
        images: [
          "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=2670&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Volkswagen",
        model: "Golf 7 GTI",
        year: 2018,
        price: 345000,
        mileage: 62000,
        fuelType: "Petrol",
        transmission: "DSG",
        engineSize: "2.0L TSI",
        color: "Red",
        bodyType: "Hatchback",
        description:
          "The iconic Golf GTI offers thrilling performance and everyday practicality. This hot hatch features the acclaimed 2.0L TSI engine, DSG transmission, and the distinctive GTI styling that has made it a legend.",
        features: [
          "GTI Sport Seats",
          "Digital Cockpit",
          "Adaptive Cruise Control",
          "Apple CarPlay",
          "Android Auto",
          "18\" GTI Alloys",
          "Fog Lights",
          "Sports Suspension",
        ],
        images: [
          "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=2670&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Toyota",
        model: "Hilux 2.8 GD-6 Legend",
        year: 2021,
        price: 625000,
        mileage: 28000,
        fuelType: "Diesel",
        transmission: "Automatic",
        engineSize: "2.8L Diesel",
        color: "Grey",
        bodyType: "Bakkie",
        description:
          "The Toyota Hilux Legend represents the pinnacle of the workhorse bakkie. This 2.8 GD-6 variant delivers exceptional power and torque while maintaining Toyota's legendary reliability. Ready for both work and adventure.",
        features: [
          "4x4 Capability",
          "Diff Lock",
          "Leather Seats",
          "Touchscreen Display",
          "Tow Bar",
          "Load Bay Cover",
          "Running Boards",
          "LED Fog Lights",
        ],
        images: [
          "https://images.unsplash.com/photo-1559416523-140ddc3d238c?q=80&w=2574&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Ford",
        model: "Ranger Wildtrak",
        year: 2020,
        price: 545000,
        mileage: 55000,
        fuelType: "Diesel",
        transmission: "Automatic",
        engineSize: "2.0L Bi-Turbo",
        color: "Blue",
        bodyType: "Bakkie",
        description:
          "The Ford Ranger Wildtrak is the ultimate lifestyle bakkie. With its bold styling, bi-turbo diesel engine, and comprehensive list of features, it's designed for those who refuse to compromise between work capability and lifestyle luxury.",
        features: [
          "Bi-Turbo Engine",
          "SYNC 3 Infotainment",
          "Leather Seats",
          "Adaptive Cruise",
          "Lane Keep Assist",
          "Sports Bar",
          "Wildtrak Decals",
          "18\" Alloys",
        ],
        images: [
          "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=2670&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Audi",
        model: "A4 2.0 TFSI S-Line",
        year: 2019,
        price: 465000,
        mileage: 48000,
        fuelType: "Petrol",
        transmission: "S-Tronic",
        engineSize: "2.0L TFSI",
        color: "White",
        bodyType: "Sedan",
        description:
          "The Audi A4 S-Line combines understated elegance with sporting intent. This TFSI variant offers smooth power delivery, quattro-like precision handling, and the timeless design language that defines the Audi brand.",
        features: [
          "S-Line Exterior",
          "Virtual Cockpit",
          "MMI Navigation",
          "Bang & Olufsen Sound",
          "Matrix LED Lights",
          "Drive Select",
          "Parking Sensors",
          "Wireless Charging",
        ],
        images: [
          "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=2670&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Hyundai",
        model: "Tucson 2.0 Elite",
        year: 2022,
        price: 425000,
        mileage: 18000,
        fuelType: "Petrol",
        transmission: "Automatic",
        engineSize: "2.0L",
        color: "Green",
        bodyType: "SUV",
        description:
          "The all-new Hyundai Tucson Elite redefines the compact SUV segment with its bold parametric design and comprehensive feature list. Low mileage and still under manufacturer warranty, this is exceptional value.",
        features: [
          "Panoramic Sunroof",
          "10.25\" Touchscreen",
          "Wireless Android Auto",
          "Blind Spot Monitor",
          "Smart Park Assist",
          "19\" Alloys",
          "LED Headlights",
          "Ventilated Seats",
        ],
        images: [
          "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=2564&auto=format&fit=crop",
        ],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
    ];

    for (const car of demoCars) {
      await ctx.db.insert("cars", car);
    }

    return { message: "Database seeded successfully", count: demoCars.length };
  },
});
